notifications:
  email: false

rvm:
  - 2.1
  - 2.0
  - 1.9.3
  - jruby-19mode

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
